ingestion {
  spark {
    app-name = "data-ingestion"
    master = "local[*]"
  }

  kafka {
    bootstrap-servers = "localhost:9092"
    schema-registry-url = "http://localhost:8081"
  }

  defaults {
    max-offsets-per-trigger = 100000
    processing-mode = "append"
    optimize-after-write = true
    vacuum-enabled = false
    vacuum-retention-hours = 168
  }
}
